// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HouseholdMapController from "./household_map_controller"
application.register("household-map", HouseholdMapController)

import VisitRouteMapController from "./visit_route_map_controller"
application.register("visit-route-map", VisitRouteMapController)

import SupplyItemFormController from "./supply_item_form_controller"
application.register("supply-item-form", SupplyItemFormController)

import HomeVisitCampaignFormController from "./home_visit_campaign_form_controller"
application.register("home-visit-campaign-form", HomeVisitCampaignFormController)

import ReferenceDomainAutocompleteController from "./reference_domain_autocomplete_controller"
application.register("reference-domain-autocomplete", ReferenceDomainAutocompleteController)
